# Generated by Django 4.1.12 on 2023-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='videos/')),
            ],
        ),
    ]
