# Generated by Django 4.1.12 on 2023-10-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blog_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='blog_images/')),
                ('video', models.FileField(blank=True, upload_to='blog_videos/')),
            ],
        ),
    ]
