# Generated by Django 4.1.12 on 2023-10-26 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_blog_image_alter_profile_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/blog_videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mov', 'mkv', 'wmv', 'flv', '3gp', 'webm'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='images/blogcover_image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.FileField(blank=True, upload_to='images/profile_image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
    ]
