# Generated by Django 4.1.12 on 2023-10-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.SmallIntegerField(blank=True, max_length=10),
        ),
    ]
